import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import jsreport from '@jsreport/browser-client';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function btnGenerate() {

    // uncomment this code
    jsreport.serverUrl = "http://localhost:5488"
    jsreport.headers['Authorization'] = "Basic " + btoa("admin:12345")

    const report = await jsreport.render({
      template: {
        content: 'Hello from {{message}}',
        engine: 'handlebars',
        recipe: 'chrome-pdf'
      },
    });

    report.openInWindow({ title: "My Quotation" })
    
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       

        <button onClick={btnGenerate}>Generate Report</button>

       
      </main>
    </>
  )
}
